package com.dickanirwansyah.spring.entities;
// Generated Oct 18, 2017 8:24:29 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Menu generated by hbm2java
 */

@Entity
@Table(name = "menu", 
        catalog = "dynamicmenu")
public class Menu  implements Serializable {

  @Id @Column(name = "idmenu", nullable = false)
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int idmenu;
 
  @ManyToOne(cascade = {CascadeType.ALL})
  @JoinColumn(name = "parentid")
  @NotFound(action = NotFoundAction.IGNORE)
  private Menu menu;
  
  @Column(name = "nama", nullable = false)
  private String nama;
  
  @Column(name = "link", nullable = false)
  private String link;
  
  @OneToMany(mappedBy = "menu", fetch = FetchType.EAGER,
          cascade = CascadeType.ALL)
  @NotFound(action = NotFoundAction.IGNORE)
  private Set<Menu> subMenus;

    public int getIdmenu() {
        return idmenu;
    }

    public void setIdmenu(int idmenu) {
        this.idmenu = idmenu;
    }

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Set<Menu> getSubMenus() {
        return subMenus;
    }

    public void setSubMenus(Set<Menu> subMenus) {
        this.subMenus = subMenus;
    }
  
  
}


